name: Machine Image Build

on: [push]

jobs:
    packer-build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: packer
        steps:
            - name: Checkout the Source Code
              uses: "actions/checkout@v3"

            - name: Connect with GCP Authentication

              uses: "google-github-actions/auth@v1"
              with:
                  credentials_json: ${{ secrets.GCP_CREDENTIALS }}

            - name: Setup Packer for running
              uses: hashicorp/setup-packer@main
              with:
                  version: "latest"

            - name: Packer Init Command
              run: "packer init $GITHUB_WORKSPACE/packer/templates/."

            - name: Packer Validate Command
              run: 'packer validate -var "project_id=${{ secrets.PROJECT_ID }}" -var "source_image_family=${{ secrets.SOURCE_IMAGE_FAMILY }}" -var "ssh_username=${{ secrets.SSH_USERNAME }}" -var "zone=${{ secrets.ZONE }}" -var "machine_type=${{ secrets.MACHINE_TYPE }}"  $GITHUB_WORKSPACE/packer/templates/. '

            - name: Packer Build Command
              run: 'packer build -var "project_id=${{ secrets.PROJECT_ID }}" -var "source_image_family=${{ secrets.SOURCE_IMAGE_FAMILY }}" -var "ssh_username=${{ secrets.SSH_USERNAME }}" -var "zone=${{ secrets.ZONE }}" -var "machine_type=${{ secrets.MACHINE_TYPE }}"  $GITHUB_WORKSPACE/packer/templates/. '
